version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    command: foreman start -f Procfile.dev
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - '.:/usr/src/app'

volumes:
  postgres:
